### ISSUE TITLE
documentation of EmptySemiEchelonBasis seems to be incorrect

### ISSUE THREAD

**Issue by klauslux** [gap-packages/cvec#1]
According to the online help EmptySemiEchelonBasis
expects a cvec.

 6.1-1 EmptySemiEchelonBasis
  
  ‣ EmptySemiEchelonBasis( v ) ──────────────────────────────────────── method
  Returns:  a new mutable empty semi echelonised basis
  
  The argument v must be a sample vector.

However, as the following code indicates this is not correct:
gap> id:=IdentityMat(3,Z(3)^0);                                       
[ [ Z(3)^0, 0*Z(3), 0*Z(3) ], [ 0*Z(3), Z(3)^0, 0*Z(3) ], 
  [ 0*Z(3), 0*Z(3), Z(3)^0 ] ]
gap> c:=CMat(id);
<cmat 3x3 over GF(3,1)>
gap> EmptySemiEchelonBasis(c[1]);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `EmptySemiEchelonBasis' on 1 arguments called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at line 13 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
What works is:
gap> EmptySemiEchelonBasis(c);
<semi echelonized basis over GF(3) of length 0>

**Comment by fingolfin** [comment]
Confirmed. There are several ways to resolve this:
1. Change the documentation to document reality
2. Add a method as described by the documentation.
3. Do both.

In either case, the current `EmptySemiEchelonBasis` should be retained to ensure existing code keeps working. But documenting it would make it official, and I am not sure whether that's desirable?

Any thoughts or preferences?

**Comment by klauslux** [comment]
On 07/14/2015 05:09 PM, Max Horn wrote:
>
> Confirmed. There are several ways to resolve this:
> 1. Change the documentation to document reality
> 2. Add a method as described by the documentation.
>
> 3. Do both.
>
  3) would be preferable.

**Comment by fingolfin** [comment]
This has been resolved in cvec 2.5.4
