### ISSUE TITLE
cvec installs IO's SIGCHLD handler on startup

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/cvec#12]
During startup, cvec calls IO_Popen on hostname, which causes IO_'s SIGCHLD handler to be activated.

This means loading cvec breaks GAP's built in child process handling.

Not sure the best way to fix this, mainly noting it down for now.

**Comment by fingolfin** [comment]
I guess the best way is to finish and merge https://github.com/gap-packages/io/pull/55 and https://github.com/gap-system/gap/pull/1851 ?

**Comment by ChrisJefferson** [comment]
That will fix it. I actually have a direct fix too, using `IO_gethostname` instead of calling out to the external `hostname` executable, which is probably better practice anyway.

**Comment by ChrisJefferson** [comment]
Fixed
