### ISSUE TITLE
manual bug

### ISSUE THREAD

**Issue by klauslux** [gap-packages/cvec#2]
The manual describes the function SemiEchelonRows, which does not exist anymore.
I suggest to get rid off the description in the manual.

**Comment by fingolfin** [comment]
Hmm, looking at the repository history, isn't it just that `SemiEchelonRows` and its many siblings were renamed to `SemiEchelonBasisMutable` etc?

**Comment by fingolfin** [comment]
This has been resolved in cvec 2.5.4
