### ISSUE TITLE
SemiEchelonRows

### ISSUE THREAD

**Issue by klauslux** [gap-packages/cvec#4]
The function SemiEchelonRows is in the GAP documentation:
just type ?SemiEchelonRows
however function no longer seems to exist. just type:
gap> SemiEchelonRows;                                                 
Error, Variable: 'SemiEchelonRows' must have a value
not in any function at line 6 of *stdin*

**Comment by fingolfin** [comment]
This was fixed in 2.5.4, I think which version of cvec are you using?

**Comment by klauslux** [comment]
Lieber Max,
so wie es aussieht, haben die Rechner am Lehrrstuhl D in Aachen noch
cvec 2.5.3., ich bitte um Entschuldigung...(und gap 4.7.6 :-))
Viele Gruesse,
Klaus.
